Test Task 1
mbilschuk/TestTask1_ pull request #1
Opened 2022-01-27 13:58 UTC by mbilschuk

**TestTask1**
Console command to read CSV file, parse the contents and insert it into a database

This pull request include only manually created files.
Files of frameworks are not included.

Requirements:

PHP: 7.4
Symphony: 5.4
Mysql:  8.0

Usage:

`php console/bin  stock.csv`

In test mode without inserted items 

`php console/bin  stock.csv --test`

Report with errors will be saved in file **stock.error.csv**

Run unit-tests

` php ./vendor/bin/phpunit`

2022-01-27 13:58 UTC, mbilschuk commented
All files can be found here
https://github.com/mbilschuk/TestTask1

2022-01-28 10:51 UTC, MrCoast requested changes

2022-01-28 10:51 UTC, MrCoast commented on src/Command/ImportCommand.php
> +    const InputFileHeaderFields = [
please move this mapping into yaml config

2022-01-28 10:51 UTC, MrCoast commented on src/Command/ImportCommand.php
> +    const AllowedCurrencies = [
please move this mapping into yaml config

2022-01-28 10:51 UTC, MrCoast commented on src/Command/ImportCommand.php
> +    const XE_API_ID = 'test97148959';
please move this into .env.dist

2022-01-28 10:51 UTC, MrCoast commented on src/Command/ImportCommand.php
> +    private float $exchangeRate = 1.000;
currencies converting is not the responsibility of the command (SRP principle)

2022-01-28 10:51 UTC, MrCoast commented on src/Command/ImportCommand.php
> +    public function getDoctrine(): ManagerRegistry {
command shouldn't know about any ORM / database layer (SRP principle)

2022-01-28 10:51 UTC, MrCoast commented on src/Command/ImportCommand.php
> +            fn($r) => !(($r->getNumPrice() < 5.0) && ($r->getIntStock() < 10)),
Symfony Validation component should be used, and this is not the responsibility of the command - see SRP principle

2022-01-28 10:51 UTC, MrCoast commented on src/Command/ImportCommand.php
> +        return $path_parts['dirname'].'/'.$path_parts['filename'].'.error.'.$path_parts['extension'];
Symfony Finder component might be used for this - and anyway this logic should not be in the command, it might be placed in some filesystem helper

2022-01-28 10:51 UTC, MrCoast commented on src/Command/ImportCommand.php
> +            throw new ImportCommandFatalException('File "'.$this->fileName.'" is not found');
sprintf() is in Symfony standard for constructing string messages - intead of concatenation

2022-01-28 10:51 UTC, MrCoast commented on src/Command/ImportCommand.php
> +        $ch = curl_init();
move all this stuff to a separate service

2022-01-28 10:51 UTC, MrCoast commented on src/Command/ImportCommand.php
> +        $this->inputFileHandle = @fopen($this->fileName, 'r');
some OOP reader library should be used instead, because this current approach is not testable

2022-01-28 10:51 UTC, MrCoast commented on src/Command/ImportCommand.php
> +        $header_data = fgetcsv($this->inputFileHandle);
all this stuff should be in a separate service class

2022-01-28 10:51 UTC, MrCoast commented on src/Command/ImportCommand.php
> +    private function checkNumPriceField(string $value): float {
all validations should be done via Symfony Validation component

2022-01-28 10:51 UTC, MrCoast commented on src/Command/ImportCommand.php
> +            $this->doctrine->getManager()->flush();
batch flushing (e.g. each 100 records) should be implemented for better performance

2022-01-28 10:51 UTC, MrCoast commented on src/Entity/TblProductData.php
> +class TblProductData
entity class and fields should be named without Hungarian notation (unlike database stuff which is fine according to the task)

2022-01-28 10:51 UTC, MrCoast commented on src/Entity/TblProductData.php
> +
no need for these empty lines,
please ensure you set up phpcs / phpstan / psalm with proper coding guideline rules

2022-01-28 10:51 UTC, MrCoast commented on tests/ImportCommandTest.php
> +class ImportCommandTest extends KernelTestCase
this test looks good as a functional tests
but please add also unit tests AFTER you implement proper project OOP structure - mentioned in other comments

2022-01-28 10:51 UTC, MrCoast commented on src/Command/ImportCommand.php
> +
there is no composer.json, docker-compose.yml and other files in the repository - you should add these
so I could clone your repository and easily run your project locally via one/two simple commands (and describe these in your README) - because currently it's impossible

2022-01-28 14:04 UTC, mbilschuk commented on src/Entity/TblProductData.php
> +class TblProductData
Done

2022-01-28 14:04 UTC, mbilschuk commented on src/Entity/TblProductData.php
> +
Done

2022-01-28 18:25 UTC, mbilschuk commented on src/Command/ImportCommand.php
> +    const XE_API_ID = 'test97148959';
Done

2022-01-28 18:26 UTC, mbilschuk commented on src/Command/ImportCommand.php
> +    private float $exchangeRate = 1.000;
Move CurrencyExchange to special service

2022-01-28 18:26 UTC, mbilschuk commented on src/Command/ImportCommand.php
> +    const InputFileHeaderFields = [
Done

2022-01-28 18:26 UTC, mbilschuk commented on src/Command/ImportCommand.php
> +    const AllowedCurrencies = [
Done

2022-01-28 19:50 UTC, mbilschuk commented on src/Command/ImportCommand.php
> +            $this->doctrine->getManager()->flush();
Done

2022-01-28 22:00 UTC, mbilschuk commented on src/Command/ImportCommand.php
> +    public function getDoctrine(): ManagerRegistry {
Created special class save record

2022-01-30 21:01 UTC, mbilschuk commented on src/Command/ImportCommand.php
> +        return $path_parts['dirname'].'/'.$path_parts['filename'].'.error.'.$path_parts['extension'];
Now I use **FileSystem** for this purpose

2022-01-30 21:19 UTC, mbilschuk commented on src/Command/ImportCommand.php
> +            throw new ImportCommandFatalException('File "'.$this->fileName.'" is not found');
Done

2022-01-30 21:20 UTC, mbilschuk commented on src/Command/ImportCommand.php
> +        $ch = curl_init();
Currency exchange is moved to special service

2022-01-30 21:21 UTC, mbilschuk commented on src/Command/ImportCommand.php
> +        $this->inputFileHandle = @fopen($this->fileName, 'r');
Now to read and parse CSV file I use league/csv package and special service **ImportFileCSVReader**

2022-01-30 21:22 UTC, mbilschuk commented on src/Command/ImportCommand.php
> +        $header_data = fgetcsv($this->inputFileHandle);
Now to read and parse CSV file I use league/csv package and special class ImportFileCSVReader

2022-01-30 21:22 UTC, mbilschuk commented on src/Command/ImportCommand.php
> +    private function checkNumPriceField(string $value): float {
Done

2022-01-31 07:50 UTC, mbilschuk commented on src/Command/ImportCommand.php
> +
I wrote correct README file

2022-01-31 07:56 UTC, mbilschuk commented on src/Command/ImportCommand.php
> +            fn($r) => !(($r->getNumPrice() < 5.0) && ($r->getIntStock() < 10)),
I added validation through **Symfony/Validation**
including custom constraint to test complex rule (Price and Stock together)

2022-02-01 18:17 UTC, closed without merging